import { lazy, Suspense, useEffect, useState } from 'react'
import { BrowserRouter, Navigate, Route, Routes, useNavigate } from 'react-router-dom'
import './App.css'; import './auth.css'; import './map.css'; import './analytics.css'; import './driver.css'; import './owner.css'; import './overrides.css'; import './notifications.css'; import './voice.css'; import './proof.css'; import './premium.css'
import { api } from './services/api'
import { connectRealtime } from './services/socket'
import { flushOfflineQueue } from './services/offlineQueue'
import AuthPortal from './features/auth/AuthPortal'
import OwnerPortal from './features/owner/OwnerPortal'
import DriverPortal from './features/driver/DriverPortal'
import WorkerPortal from './features/worker/WorkerPortal'
import NotificationCenter from './NotificationCenter'
import ProtectedRoute from './routes/ProtectedRoute'

const FleetMap = lazy(() => import('./features/fleet/FleetMap'))
const AnalyticsPanel = lazy(() => import('./AnalyticsPanel'))
const TrainingPage = lazy(() => import('./features/worker/TrainingPage'))
const fallbackTickets = [{ id: 'UT-2048', vehicle: 'TRUCK #245', fault: 'Battery Voltage Instability', risk: 'IMMEDIATE', rootCause: 'Alternator regulator fluctuation', status: 'ASSIGNED', deadline: '2026-08-15T15:00:00Z' }, { id: 'UT-2047', vehicle: 'TRUCK #302', fault: 'Wiring Fault', risk: 'IMMEDIATE', rootCause: 'Damaged harness insulation', status: 'IN_PROGRESS', deadline: '2026-08-15T13:30:00Z' }, { id: 'UT-2043', vehicle: 'TRUCK #118', fault: 'Brake Pad Wear', risk: 'SHORT-TERM', rootCause: 'Pad thickness below threshold', status: 'ASSIGNED', deadline: '2026-08-16T10:00:00Z' }]
const fallbackWorkers = [{ id: 'worker-1', name: 'Asha Nair', status: 'AVAILABLE', attendance: 'CHECKED_IN' }, { id: 'worker-2', name: 'Maria Silva', status: 'BUSY', attendance: 'CHECKED_IN' }, { id: 'worker-3', name: 'Dev Kumar', status: 'AVAILABLE', attendance: 'CHECKED_IN' }]
const fallbackVehicles = ['245','118','302','091','411','633','277','510','709','830','904','125'].map((number,index)=>({id:`vehicle-${number}`,vehicleId:`TRUCK #${number}`,health:index===0?42:index===2?38:68+index*2,status:index===0?'IN_GARAGE':index===2?'REPAIRING':'ON_ROAD'}))

export default function App() { return <BrowserRouter><UTAPApp/></BrowserRouter> }

function UTAPApp() {
  const navigate = useNavigate()
  const [auth,setAuth] = useState(()=>JSON.parse(localStorage.getItem('utap-session')||'null'))
  const [tickets,setTickets] = useState(fallbackTickets), [workers,setWorkers] = useState(fallbackWorkers), [vehicles,setVehicles] = useState(fallbackVehicles)
  const [notice,setNotice] = useState('Live telemetry connected · demo fleet reporting'), [selected,setSelected] = useState(null), [online,setOnline] = useState(navigator.onLine)
  useEffect(()=>{if(!auth?.token)return;api.me().then(({user})=>setAuth(current=>{const refreshed={...current,...user};localStorage.setItem('utap-session',JSON.stringify(refreshed));return refreshed})).catch(()=>{localStorage.removeItem('utap-session');setAuth(null);navigate('/login',{replace:true})})},[auth?.token,navigate])
  useEffect(()=>{ if(!auth?.token)return; api.tickets({limit:50}).then(result=>setTickets(result.items||[])).catch(()=>setNotice('Using retained task data while the API reconnects.')); api.vehicles({limit:50}).then(result=>setVehicles(result.items||[])).catch(()=>{}); if(auth.role==='OWNER')api.workers().then(setWorkers).catch(()=>{}); return connectRealtime(auth,{'ticket:created':ticket=>{setTickets(items=>[ticket,...items]);setNotice(`New ${ticket.risk} risk detected for ${ticket.vehicle}.`)},'ticket:updated':ticket=>{setTickets(items=>items.map(item=>item.id===ticket.id?{...item,...ticket}:item));setNotice(`${ticket.vehicle} repair workflow updated.`)},'notification:new':item=>setNotice(item.message)})},[auth])
  useEffect(()=>{const up=async()=>{setOnline(true);const count=await flushOfflineQueue(api);setNotice(count?`${count} queued action(s) synced.`:'Connection restored · live updates reconnected.')},down=()=>{setOnline(false);setNotice('You are offline. Current task data remains available.')};window.addEventListener('online',up);window.addEventListener('offline',down);return()=>{window.removeEventListener('online',up);window.removeEventListener('offline',down)}},[])
  const login=session=>{const next={...session,organizationId:session.organizationId||'abc-logistics'};localStorage.setItem('utap-session',JSON.stringify(next));setAuth(next);navigate(`/${next.role.toLowerCase()}/dashboard`,{replace:true})}
  const logout=()=>{api.logout().catch(()=>{});localStorage.removeItem('utap-session');setAuth(null);navigate('/login',{replace:true})}
  const updateTicket=updated=>setTickets(items=>items.map(item=>item.id===updated.id?{...item,...updated}:item))
  const simulate=async risk=>{try{const ticket=await api.simulate(risk);setTickets(items=>[ticket,...items]);setNotice(`New ${ticket.risk} predictive ticket created for ${ticket.vehicle}.`)}catch{setNotice('Telemetry simulator is unavailable.') }}
  const assign=async(workerId,deadline)=>{if(!selected)return;const worker=workers.find(item=>item.id===workerId);try{const ticket=await api.assign(selected.id,workerId,deadline);updateTicket({...ticket,worker:worker?.name});setNotice(`Task assigned to ${worker?.name||'technician'}.`)}catch{updateTicket({...selected,workerId,worker:worker?.name,deadline});setNotice('Assignment queued locally.')}setSelected(null)}
  const addVehicle=async payload=>{const vehicle=await api.createVehicle(payload);setVehicles(items=>[vehicle,...items]);setNotice(`${vehicle.vehicleId} was added to the fleet.`);return vehicle}
  const active=tickets.filter(ticket=>ticket.status!=='COMPLETED').length
  const shell=content=><><main>{!online&&<div className="offline" role="status">You are offline. Current work remains available and retry can continue after reconnection.</div>}<header className="top"><div className="brand"><div className="mark">U</div><div><b>UTAP</b><small>UNIFIED TELEMETRY-TO-ACTION</small></div></div><div className="live"><span/>{notice}</div><NotificationCenter latest={notice}/><button className="profile" onClick={logout} title="Log out">{auth?.name?.split(' ').map(part=>part[0]).join('')}<small>Logout</small></button></header>{content}</main>{selected&&<AssignmentModal ticket={selected} workers={workers} onClose={()=>setSelected(null)} onAssign={assign}/>}</>
  return <Routes><Route path="/login" element={auth?<Navigate to={`/${auth.role.toLowerCase()}/dashboard`} replace/>:<AuthPortal onLogin={login}/>}/><Route path="/register" element={auth?<Navigate to={`/${auth.role.toLowerCase()}/dashboard`} replace/>:<AuthPortal onLogin={login}/>}/><Route path="/forgot-password" element={<AuthPortal onLogin={login}/>}/><Route path="/reset-password" element={<AuthPortal onLogin={login}/>}/><Route path="/owner/*" element={<ProtectedRoute session={auth} role="OWNER">{shell(<OwnerPortal tickets={tickets} vehicles={vehicles} workers={workers} active={active} simulate={simulate} select={setSelected} onAddVehicle={addVehicle} map={<Suspense fallback={<div className="lazyload">Loading fleet map...</div>}><FleetMap/></Suspense>} analytics={<Suspense fallback={<div className="lazyload">Loading analytics...</div>}><AnalyticsPanel/></Suspense>}/>)}</ProtectedRoute>}/><Route path="/driver/dashboard" element={<ProtectedRoute session={auth} role="DRIVER">{shell(<DriverPortal onNotice={setNotice}/>)}</ProtectedRoute>}/><Route path="/worker/training" element={<ProtectedRoute session={auth} role="WORKER">{shell(<Suspense fallback={<div className="lazyload">Loading training sandbox...</div>}><TrainingPage/></Suspense>)}</ProtectedRoute>}/><Route path="/worker/*" element={<ProtectedRoute session={auth} role="WORKER">{shell(<WorkerPortal tickets={tickets} onNotice={setNotice} onTicketUpdated={updateTicket}/>)}</ProtectedRoute>}/><Route path="*" element={<Navigate to={auth?`/${auth.role.toLowerCase()}/dashboard`:'/login'} replace/>}/></Routes>
}

function AssignmentModal({ticket,workers,onClose,onAssign}) { const [workerId,setWorkerId]=useState(''),[deadline,setDeadline]=useState(ticket.deadline?new Date(ticket.deadline).toISOString().slice(0,16):''),[error,setError]=useState('');const submit=e=>{e.preventDefault();if(!workerId||!deadline)return setError('Select an available technician and repair deadline.');onAssign(workerId,deadline)};return <div className="modalback" role="dialog" aria-modal="true"><form className="modal" onSubmit={submit}><button type="button" className="close" onClick={onClose}>×</button><p className="eyebrow">ASSIGN REPAIR TASK</p><h2>{ticket.vehicle}</h2><p>{ticket.fault||ticket.issue}</p><label>Available technician<select required value={workerId} onChange={e=>setWorkerId(e.target.value)}><option value="">Select a worker</option>{workers.filter(worker=>worker.status==='AVAILABLE').map(worker=><option key={worker.id} value={worker.id}>{worker.name} · {worker.attendance}</option>)}</select></label><label>Repair deadline<input required type="datetime-local" value={deadline} onChange={e=>setDeadline(e.target.value)}/></label>{error&&<p className="formerror">{error}</p>}<button className="primary wide">Assign & notify worker</button></form></div> }
