import { useEffect, useState } from 'react'
import { api } from './services/api'

const fallback = { vehicle: { id: 'vehicle-245', vehicleId: 'TRUCK #245', health: 42 }, risk: 'IMMEDIATE', fault: 'Battery voltage instability', metrics: { temperature: 91, batteryVoltage: 11.4, fuel: 68, oilPressure: 31, rpm: 2100, tirePressure: 34, speed: 52, fuelEfficiency: 8.4, collisionProximity: 'Clear', ecoSuggestion: 'Maintain steady speed' } }
export default function DriverPortal({ onNotice }) {
  const [data, setData] = useState(fallback), [checkedIn, setCheckedIn] = useState(false), [message, setMessage] = useState('')
  useEffect(() => { api.driverVehicle().then(result => setData({ ...fallback, ...result, metrics: { ...fallback.metrics, ...result.metrics } })).catch(() => {}) }, [])
  const action = async (call, success) => { try { await call() } catch {} setMessage(success); onNotice(success) }
  const toggleShift = async () => { const next = !checkedIn; await action(next ? api.driverCheckIn : api.driverCheckOut, next ? 'Driver check-in recorded.' : 'Driver check-out recorded.'); setCheckedIn(next) }
  const metrics = data.metrics || fallback.metrics, critical = data.risk === 'IMMEDIATE'
  return <div className="driver"><div className="driverTop"><span>{data.vehicle.vehicleId}</span><b>{checkedIn ? 'ON DUTY' : 'READY FOR CHECK-IN'}</b></div>{critical && <section className="driveralert"><span>IMMEDIATE RISK</span><h1>{data.fault || 'Vehicle needs immediate attention'}</h1><p>Nearest garage: 4 km · Follow fleet safety guidance.</p><button onClick={() => setMessage('Alert acknowledged. Continue safely to the nearest garage.')}>Acknowledge alert</button></section>}<div className="health"><p>VEHICLE HEALTH</p><h1>{data.vehicle.health}<span>%</span></h1><div className="bar"><i style={{ width: `${data.vehicle.health}%`, background: critical ? '#ef4444' : '#22c55e' }}/></div><p>{critical ? 'Service recommended before next route.' : 'Vehicle is healthy for the assigned route.'}</p></div><div className="driverstats"><Stat n={`${metrics.temperature}°C`} l="Engine temp" d="Live telemetry"/><Stat n={`${metrics.batteryVoltage}V`} l="Battery" d={critical ? 'Low' : 'Normal'} red={critical}/><Stat n={`${metrics.fuel}%`} l="Fuel" d={`${metrics.fuelEfficiency} km/L`}/><Stat n={`${metrics.rpm}`} l="RPM" d={`Oil ${metrics.oilPressure} PSI`}/><Stat n={`${metrics.tirePressure} PSI`} l="Tires" d={`${metrics.speed} km/h`}/><Stat n={metrics.collisionProximity} l="Proximity" d={metrics.ecoSuggestion}/></div>{message && <p className="driver-message" role="status">{message}</p>}<div className="quick"><button onClick={toggleShift}><span>{checkedIn ? 'Check out' : 'Check in'}</span></button><button onClick={() => action(() => api.dvir(data.vehicle.id), 'Driver vehicle inspection report submitted.')}><span>Quick DVIR</span></button><button className="sos" onClick={() => action(() => api.sos(data.vehicle.id), 'SOS dispatched to fleet operations.')}>SOS<span>Emergency</span></button></div></div>
}
function Stat({ n, l, d, red }) { return <section className="metric"><div><span>{l}</span><h2 className={red ? 'redtext' : ''}>{n}</h2></div><small className={red ? 'redtext' : ''}>{d}</small></section> }
