import { useMemo, useState } from 'react'
import KanbanBoard from './features/tickets/KanbanBoard'
import MaintenancePage from './features/maintenance/MaintenancePage'
import OwnerAnalyticsPage from './features/analytics/OwnerAnalyticsPage'

const nav = ['Dashboard', 'Fleet', 'Vehicles', 'Workers', 'Repair Tickets', 'Maintenance', 'Alerts', 'Analytics', 'Settings']

export default function OwnerPortal({ tickets, vehicles, workers, active, simulate, select, map, analytics }) {
  const [page, setPage] = useState('Dashboard')
  const [query, setQuery] = useState('')
  const filtered = useMemo(() => tickets.filter((ticket) => `${ticket.vehicle} ${ticket.issue || ticket.fault}`.toLowerCase().includes(query.toLowerCase())), [tickets, query])
  const immediate = tickets.filter((ticket) => ticket.risk === 'IMMEDIATE' && ticket.status !== 'COMPLETED').length
  const available = workers.filter((worker) => worker.status === 'AVAILABLE').length
  return <div className="owner-shell"><aside className="owner-nav"><div className="owner-nav-brand"><b>UTAP</b><small>ABC LOGISTICS</small></div>{nav.map((item) => <button key={item} className={page === item ? 'selected' : ''} onClick={() => setPage(item)}>{item}{item === 'Repair Tickets' && <em>{active}</em>}</button>)}</aside><section className="owner-main"><header className="owner-pagehead"><div><p className="eyebrow">{page === 'Dashboard' ? 'OPERATIONS COMMAND CENTER' : page.toUpperCase()}</p><h1>{page === 'Dashboard' ? 'Good morning, Ananya' : page}</h1><p>ABC Logistics · live operational workspace</p></div>{page === 'Dashboard' && <div className="demo-controls"><button onClick={() => simulate('IMMEDIATE')}>Immediate risk</button><button onClick={() => simulate('SHORT-TERM')}>Short-term risk</button><button onClick={() => simulate('LONG-TERM')}>Long-term risk</button></div>}</header>{page === 'Dashboard' && <Dashboard tickets={tickets} vehicles={vehicles} active={active} immediate={immediate} available={available} select={select} map={map} analytics={analytics}/>} {page === 'Fleet' && <Fleet vehicles={vehicles}/>} {page === 'Vehicles' && <Vehicles vehicles={vehicles}/>} {page === 'Workers' && <Workers workers={workers}/>} {page === 'Repair Tickets' && <Tickets tickets={filtered} query={query} setQuery={setQuery} select={select}/>} {page === 'Maintenance' && <MaintenancePage/>} {page === 'Alerts' && <Alerts tickets={tickets}/>} {page === 'Analytics' && <OwnerAnalyticsPage/>} {page === 'Settings' && <Settings/>}</section></div>
}

function Dashboard({ tickets, vehicles, active, immediate, available, select, map, analytics }) { const onRoad = vehicles.filter((vehicle) => vehicle.status === 'ON_ROAD').length; return <><div className="owner-metrics"><Metric number={vehicles.length} label="Total vehicles"/><Metric number={onRoad} label="Active / on road"/><Metric number={immediate} label="Immediate risks" danger/><Metric number={active} label="Active repairs"/><Metric number={available} label="Available workers"/></div>{map}<section className="owner-card"><h2>Priority repair tickets</h2>{tickets.length ? tickets.slice(0, 4).map((ticket) => <TicketRow key={ticket.id} ticket={ticket} select={select}/>) : <p>No active repairs.</p>}</section>{analytics}</> }
function Fleet({ vehicles }) { return <section className="owner-card"><h2>Live fleet overview</h2><div className="owner-grid">{vehicles.map((vehicle) => <article key={vehicle.id}><b>{vehicle.vehicleId}</b><span>{vehicle.status.replace('_', ' ')}</span><strong className={vehicle.health < 60 ? 'redtext' : vehicle.health < 80 ? 'ambertext' : 'greentext'}>{vehicle.health}% health</strong></article>)}</div></section> }
function Vehicles({ vehicles }) { return <section className="owner-card"><h2>Vehicles</h2><div className="owner-table">{vehicles.map((vehicle) => <div key={vehicle.id}><b>{vehicle.vehicleId}</b><span>{vehicle.status.replace('_', ' ')}</span><span>{vehicle.health}%</span><span className={vehicle.health < 60 ? 'redtext' : vehicle.health < 80 ? 'ambertext' : 'greentext'}>{vehicle.health < 60 ? 'IMMEDIATE' : vehicle.health < 80 ? 'SHORT-TERM' : 'HEALTHY'}</span></div>)}</div></section> }
function Workers({ workers }) { return <section className="owner-card"><h2>Workforce availability</h2><div className="owner-table">{workers.map((worker) => <div key={worker.id}><b>{worker.name}</b><span className={worker.status === 'AVAILABLE' ? 'greentext' : worker.status === 'BUSY' ? 'ambertext' : ''}>{worker.status}</span><span>{worker.attendance.replace('_', ' ')}</span></div>)}</div></section> }
function Tickets({ tickets, query, setQuery, select }) { return <section className="owner-card"><div className="tickets-heading"><div><h2>Repair workflow</h2><p>Live ticket state updates from telemetry and technician actions.</p></div><input className="ticket-search" value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Search vehicle or fault"/></div><KanbanBoard tickets={tickets} onSelect={select}/></section> }
function TicketRow({ ticket, select }) { const risk = ticket.risk || 'SHORT-TERM'; return <div className="owner-ticket"><div><b>{ticket.vehicle}</b><span>{ticket.issue || ticket.fault}</span><small>{ticket.id} · {ticket.deadline ? new Date(ticket.deadline).toLocaleString() : 'No deadline'}</small></div><span className={risk === 'IMMEDIATE' ? 'redtext' : risk === 'SHORT-TERM' ? 'ambertext' : 'greentext'}>{risk}</span><span>{ticket.status?.replace('_', ' ')}</span><button onClick={() => select(ticket)}>{ticket.workerId ? 'View task' : 'Assign worker'}</button></div> }
function Alerts({ tickets }) { return <section className="owner-card"><h2>Predictive alerts</h2>{tickets.filter((ticket) => ticket.status !== 'COMPLETED').map((ticket) => <p key={ticket.id} className={ticket.risk === 'IMMEDIATE' ? 'redtext' : 'ambertext'}>{ticket.risk} · {ticket.vehicle} · {ticket.fault || ticket.issue}</p>)}</section> }
function Settings() { return <section className="owner-card"><h2>Settings</h2><div className="owner-grid"><article><b>Profile</b><span>Owner profile and preferences</span></article><article><b>Organization</b><span>ABC Logistics</span></article><article><b>Notifications</b><span>Immediate risks enabled</span></article><article><b>Security</b><span>JWT session active</span></article></div></section> }
function Metric({ number, label, danger }) { return <article className="owner-metric"><b className={danger ? 'redtext' : ''}>{number}</b><span>{label}</span></article> }
