import { useMemo, useState } from 'react'
import KanbanBoard from '../tickets/KanbanBoard'
import MaintenancePage from '../maintenance/MaintenancePage'
import OwnerAnalyticsPage from '../analytics/OwnerAnalyticsPage'

const nav = ['Dashboard', 'Fleet', 'Vehicles', 'Workers', 'Repair Tickets', 'Maintenance', 'Alerts', 'Analytics', 'Settings']

export default function OwnerPortal({ tickets, vehicles, workers, active, simulate, select, onAddVehicle, map, analytics }) {
  const [page, setPage] = useState('Dashboard'), [query, setQuery] = useState(''), [drawer, setDrawer] = useState(false), [adding, setAdding] = useState(false)
  const immediate = tickets.filter(t => t.risk === 'IMMEDIATE' && t.status !== 'COMPLETED').length
  const available = workers.filter(w => w.status === 'AVAILABLE').length
  const filtered = useMemo(() => tickets.filter(t => `${t.vehicle} ${t.issue || t.fault}`.toLowerCase().includes(query.toLowerCase())), [tickets, query])
  const choose = value => { setPage(value); setDrawer(false) }
  return <div className="owner-shell">{drawer && <button className="owner-drawer-backdrop" aria-label="Close navigation" onClick={() => setDrawer(false)}/>}<aside className={`owner-nav ${drawer ? 'drawer-open' : ''}`}><div className="owner-nav-brand"><b>UTAP</b><small>ABC LOGISTICS</small></div>{nav.map(item => <button key={item} className={page === item ? 'selected' : ''} onClick={() => choose(item)}>{item}{item === 'Repair Tickets' && <em>{active}</em>}</button>)}</aside><section className="owner-main"><header className="owner-pagehead"><div><button className="owner-menu" aria-label="Open navigation" onClick={() => setDrawer(true)}>☰</button><p className="eyebrow">{page === 'Dashboard' ? 'OPERATIONS COMMAND CENTER' : page.toUpperCase()}</p><h1>{page === 'Dashboard' ? 'Good morning, Ananya' : page}</h1><p>ABC Logistics · live operational workspace</p></div>{page === 'Dashboard' && <div className="demo-controls"><button onClick={() => simulate('IMMEDIATE')}>Immediate risk</button><button onClick={() => simulate('SHORT-TERM')}>Short-term risk</button><button onClick={() => simulate('LONG-TERM')}>Long-term risk</button></div>}</header>{page === 'Dashboard' && <Dashboard {...{ tickets, vehicles, active, immediate, available, select, map, analytics }}/>} {page === 'Fleet' && <Fleet vehicles={vehicles}/>} {page === 'Vehicles' && <Vehicles vehicles={vehicles} onAdd={() => setAdding(true)}/>} {page === 'Workers' && <Workers workers={workers}/>} {page === 'Repair Tickets' && <Tickets tickets={filtered} query={query} setQuery={setQuery} select={select}/>} {page === 'Maintenance' && <MaintenancePage/>} {page === 'Alerts' && <Alerts tickets={tickets}/>} {page === 'Analytics' && <OwnerAnalyticsPage/>} {page === 'Settings' && <Settings/>}</section>{adding && <AddVehicle onAdd={onAddVehicle} onClose={() => setAdding(false)}/>}</div>
}
function Dashboard({ tickets, vehicles, active, immediate, available, select, map, analytics }) { return <><div className="owner-metrics"><Metric n={vehicles.length} l="Total vehicles"/><Metric n={vehicles.filter(v => v.status === 'ON_ROAD').length} l="Active / on road"/><Metric n={immediate} l="Immediate risks" danger/><Metric n={active} l="Active repairs"/><Metric n={available} l="Available workers"/></div>{map}<section className="owner-card"><h2>Priority repair tickets</h2>{tickets.length ? tickets.slice(0, 4).map(t => <TicketRow key={t.id} ticket={t} select={select}/>) : <p>No active repairs.</p>}</section>{analytics}</> }
function Fleet({ vehicles }) { return <section className="owner-card"><h2>Live fleet overview</h2><div className="owner-grid">{vehicles.map(v => <article key={v.id}><b>{v.vehicleId}</b><span>{v.status.replace('_', ' ')}</span><strong className={tone(v.health)}>{v.health}% health</strong></article>)}</div></section> }
function Vehicles({ vehicles, onAdd }) { return <section className="owner-card"><div className="owner-section-head"><h2>Vehicles</h2><button className="primary" onClick={onAdd}>Add vehicle</button></div><div className="owner-table">{vehicles.map(v => <div key={v.id}><b>{v.vehicleId}</b><span>{v.status.replace('_', ' ')}</span><span>{v.health}%</span><span className={tone(v.health)}>{v.health < 60 ? 'IMMEDIATE' : v.health < 80 ? 'SHORT-TERM' : 'HEALTHY'}</span></div>)}</div></section> }
function Workers({ workers }) { return <section className="owner-card"><h2>Workforce availability</h2><div className="owner-table">{workers.map(w => <div key={w.id}><b>{w.name}</b><span className={w.status === 'AVAILABLE' ? 'greentext' : w.status === 'BUSY' ? 'ambertext' : ''}>{w.status}</span><span>{w.attendance.replace('_', ' ')}</span></div>)}</div></section> }
function Tickets({ tickets, query, setQuery, select }) { return <section className="owner-card"><div className="tickets-heading"><div><h2>Repair workflow</h2><p>Live ticket state updates from telemetry and technician actions.</p></div><input className="ticket-search" value={query} onChange={e => setQuery(e.target.value)} placeholder="Search vehicle or fault"/></div><KanbanBoard tickets={tickets} onSelect={select}/></section> }
function TicketRow({ ticket, select }) { return <div className="owner-ticket"><div><b>{ticket.vehicle}</b><span>{ticket.issue || ticket.fault}</span><small>{ticket.id} · {ticket.deadline ? new Date(ticket.deadline).toLocaleString() : 'No deadline'}</small></div><span className={ticket.risk === 'IMMEDIATE' ? 'redtext' : ticket.risk === 'SHORT-TERM' ? 'ambertext' : 'greentext'}>{ticket.risk}</span><span>{ticket.status?.replace('_', ' ')}</span><button onClick={() => select(ticket)}>{ticket.workerId ? 'View task' : 'Assign worker'}</button></div> }
function Alerts({ tickets }) { return <section className="owner-card"><h2>Predictive alerts</h2>{tickets.filter(t => t.status !== 'COMPLETED').map(t => <p key={t.id} className={t.risk === 'IMMEDIATE' ? 'redtext' : 'ambertext'}>{t.risk} · {t.vehicle} · {t.fault || t.issue}</p>)}</section> }
function Settings() { return <section className="owner-card"><h2>Settings</h2><div className="owner-grid">{['Profile','Organization','Notifications','Security'].map(x => <article key={x}><b>{x}</b><span>{x === 'Organization' ? 'ABC Logistics' : `${x} preferences`}</span></article>)}</div></section> }
function Metric({ n, l, danger }) { return <article className="owner-metric"><b className={danger ? 'redtext' : ''}>{n}</b><span>{l}</span></article> }
const tone = health => health < 60 ? 'redtext' : health < 80 ? 'ambertext' : 'greentext'
function AddVehicle({ onClose, onAdd }) { const [data, setData] = useState({ vehicleId:'', driverId:'', status:'ON_ROAD', health:100 }), [busy,setBusy] = useState(false), [error,setError] = useState(''); const set = (key,value) => setData(d => ({...d,[key]:value})); const submit = async e => {e.preventDefault();setBusy(true);setError('');try{await onAdd({...data,driverId:data.driverId||null,health:Number(data.health)});onClose()}catch(err){setError(err.message||'Unable to add vehicle.')}finally{setBusy(false)}}; return <div className="modalback" role="dialog" aria-modal="true"><form className="modal" onSubmit={submit}><button className="close" type="button" onClick={onClose}>×</button><p className="eyebrow">FLEET SETUP</p><h2>Add vehicle</h2><label>Vehicle ID<input required placeholder="TRUCK #451" value={data.vehicleId} onChange={e=>set('vehicleId',e.target.value)}/></label><label>Driver ID <small>(optional)</small><input value={data.driverId} onChange={e=>set('driverId',e.target.value)}/></label><label>Initial status<select value={data.status} onChange={e=>set('status',e.target.value)}><option value="ON_ROAD">On road</option><option value="IDLE">Idle</option><option value="IN_GARAGE">In garage</option><option value="OUT_OF_SERVICE">Out of service</option></select></label><label>Initial health (%)<input required type="number" min="0" max="100" value={data.health} onChange={e=>set('health',e.target.value)}/></label>{error&&<p className="formerror">{error}</p>}<button disabled={busy} className="primary wide">{busy?'Adding vehicle…':'Add vehicle'}</button></form></div> }
