import 'dotenv/config'
import express from 'express'
import cors from 'cors'
import jwt from 'jsonwebtoken'
import bcrypt from 'bcryptjs'
import { createServer } from 'node:http'
import { Server } from 'socket.io'
import crypto from 'node:crypto'
import mongoose from 'mongoose'
import { answerRepairQuestion } from './services/repairAssistant.js'
import { connectDatabase } from './config/database.js'
import { errorHandler, notFound } from './middleware/errorHandler.js'
import { rateLimit } from './middleware/rateLimit.js'
import { createAuth } from './middleware/auth.js'
import { scoped } from './middleware/org-scope.js'
import { Organization, User, Vehicle, RepairTicket, MaintenanceRecord, Notification, AuditLog, ARProcedure, SensorReading, Prediction } from './models.js'
import { predictMaintenance } from './services/predictionEngine.js'
import { saveRepairProof } from './services/proofStorage.js'
import { sendPasswordResetEmail } from './services/emailService.js'
import path from 'node:path'

const app = express(), http = createServer(app)
if (process.env.NODE_ENV === 'production' && !process.env.JWT_SECRET) throw new Error('JWT_SECRET is required in production.')
const jwtSecret = process.env.JWT_SECRET || 'development-secret'
const io = new Server(http, { cors: { origin: process.env.CLIENT_URL || 'http://localhost:5173' } })
app.use(cors({ origin: process.env.CLIENT_URL || 'http://localhost:5173' }))
app.use(express.json({ limit: '2mb' }))
app.use('/uploads', express.static(process.env.REPAIR_STORAGE_PATH || path.resolve('uploads')))
const authLimiter = rateLimit({ windowMs: 60_000, max: 10 })
const org = 'abc-logistics', hash = bcrypt.hashSync('Demo@123', 10)
const users = [['owner-1','Ananya Kapoor','owner@utap.demo','OWNER'],['driver-1','Arjun Mehta','driver@utap.demo','DRIVER'],['worker-1','Asha Nair','worker@utap.demo','WORKER'],['worker-2','Maria Silva','maria@utap.demo','WORKER'],['worker-3','Dev Kumar','dev@utap.demo','WORKER']].map(([id,name,email,role])=>({id,name,email,role,organizationId:org,password:hash,active:true}))
const vehicles = ['245','118','302','091','411','633','277','510','709','830','904','125'].map((id,index)=>({id:`vehicle-${id}`,organizationId:org,vehicleId:`TRUCK #${id}`,driverId:index===0?'driver-1':null,status:index===0?'IN_GARAGE':index===2?'REPAIRING':'ON_ROAD',health:index===0?42:index===2?38:Math.min(98,65+index*3),lat:13.05+index*.012,lng:80.2+index*.01}))
let tickets = [{id:'UT-2048',organizationId:org,vehicleId:'vehicle-245',vehicle:'TRUCK #245',fault:'Battery Voltage Instability',risk:'IMMEDIATE',rootCause:'Alternator regulator fluctuation',status:'ASSIGNED',workerId:null,deadline:'2026-08-15T15:00:00Z'},{id:'UT-2047',organizationId:org,vehicleId:'vehicle-302',vehicle:'TRUCK #302',fault:'Wiring Fault',risk:'IMMEDIATE',rootCause:'Damaged harness insulation',status:'IN_PROGRESS',workerId:'worker-2',deadline:'2026-08-15T13:30:00Z'},{id:'UT-2043',organizationId:org,vehicleId:'vehicle-118',vehicle:'TRUCK #118',fault:'Brake Pad Wear',risk:'SHORT-TERM',rootCause:'Pad thickness below threshold',status:'ASSIGNED',workerId:'worker-3',deadline:'2026-08-16T10:00:00Z'}]
let notifications = [], records = [], audits = []
const resetTokens = new Map()
let mongoEnabled = false
const audit = (user,action,entity,entityId)=>audits.unshift({id:`audit-${Date.now()}`,organizationId:user.organizationId,userId:user.id,action,entity,entityId,timestamp:new Date().toISOString()})
const notify = (organizationId,userId,message)=>{const n={id:`notice-${Date.now()}`,organizationId,userId,message,read:false,timestamp:new Date().toISOString()};notifications.unshift(n);io.to(userId||organizationId).emit('notification:new',n);return n}
const auth = createAuth(jwtSecret)
const paged = (rows, query = {}) => { const page=Math.max(1,Number(query.page)||1),limit=Math.min(100,Math.max(1,Number(query.limit)||20)),start=(page-1)*limit; return { items: rows.slice(start,start+limit), page, limit, total: rows.length, totalPages: Math.ceil(rows.length/limit) } }
const serializeTicket = ticket => ({ id:String(ticket._id||ticket.id), organizationId:String(ticket.organizationId), vehicleId:String(ticket.vehicleId?._id||ticket.vehicleId), vehicle:ticket.vehicleId?.vehicleId||ticket.vehicle||'', fault:ticket.fault, issue:ticket.fault||ticket.issue, risk:ticket.risk, rootCause:ticket.rootCause, confidence:ticket.confidence, status:ticket.status, workerId:ticket.workerId?String(ticket.workerId._id||ticket.workerId):null, deadline:ticket.deadline, due:ticket.deadline })
const serializeVehicle = vehicle => ({ id:String(vehicle._id||vehicle.id), organizationId:String(vehicle.organizationId), vehicleId:vehicle.vehicleId, driverId:vehicle.driverId?String(vehicle.driverId._id||vehicle.driverId):null, status:vehicle.status, health:vehicle.health, location:vehicle.location||{lat:vehicle.lat,lng:vehicle.lng} })

app.get('/api/health',(_,res)=>res.json({status:'ok',mode:'demo-fallback'}))
app.post('/api/auth/register',authLimiter,async(req,res)=>{const {name,email,password,role,organizationName,profile={}}=req.body;const safeProfile=Object.fromEntries(Object.entries(profile).filter(([key])=>!['password','confirmPassword'].includes(key)));if(!name||!email||!password||password.length<8||!['OWNER','DRIVER','WORKER'].includes(role))return res.status(400).json({message:'Please provide valid registration details.'});if(mongoEnabled){if(await User.findOne({email}))return res.status(409).json({message:'An account with this email already exists.'});let organizationId=safeProfile.organizationId;if(role==='OWNER'){const organization=await Organization.create({name:organizationName||`${name}'s organization`,type:safeProfile.organizationType,location:safeProfile.location,fleetSize:Number(safeProfile.fleetSize)||0});organizationId=organization._id}if(!organizationId)return res.status(400).json({message:'An organization is required for driver and worker registration.'});await User.create({organizationId,name,email,passwordHash:await bcrypt.hash(password,10),role,profile:safeProfile,active:true});return res.status(201).json({message:'Registration successful. Please sign in.'})}if(users.some(u=>u.email===email))return res.status(409).json({message:'An account with this email already exists.'});const organizationId=role==='OWNER'?`org-${Date.now()}`:safeProfile.organizationId;if(!organizationId)return res.status(400).json({message:'An organization is required for driver and worker registration.'});users.push({id:`user-${Date.now()}`,name,email,password:await bcrypt.hash(password,10),role,organizationId,active:true,organizationName,profile:safeProfile});res.status(201).json({message:'Registration successful. Please sign in.'})})
app.post('/api/auth/login',authLimiter,async(req,res)=>{const {email,password,portal}=req.body;let u=users.find(x=>x.email===email);if(mongoEnabled){const dbUser=await User.findOne({email});if(dbUser)u={id:String(dbUser._id),name:dbUser.name,email:dbUser.email,password:dbUser.passwordHash,role:dbUser.role,organizationId:String(dbUser.organizationId),active:dbUser.active}}if(!u||!await bcrypt.compare(password||'',u.password))return res.status(401).json({message:'Invalid email or password.'});if(!u.active)return res.status(403).json({message:'This account is inactive.'});if(portal&&u.role!==portal.toUpperCase())return res.status(403).json({message:'This account is not registered for the selected portal. Please select the correct portal.'});audit(u,'LOGIN','User',u.id);const token=jwt.sign({id:u.id,name:u.name,role:u.role,organizationId:u.organizationId},jwtSecret,{expiresIn:'8h'});res.json({token,user:{id:u.id,name:u.name,email:u.email,role:u.role,organizationId:u.organizationId}})})
app.post('/api/auth/logout',auth(),async(req,res)=>{if(mongoEnabled)await AuditLog.create({organizationId:req.user.organizationId,userId:req.user.id,action:'LOGOUT',entity:'User',entityId:req.user.id});else audit(req.user,'LOGOUT','User',req.user.id);res.json({message:'Logged out.'})})
app.get('/api/auth/me',auth(),(req,res)=>res.json({user:{id:req.user.id,name:req.user.name,email:req.user.email,role:req.user.role,organizationId:req.user.organizationId}}))
app.post('/api/auth/forgot-password',authLimiter,async(req,res)=>{let user=users.find(item=>item.email===req.body.email);if(mongoEnabled){const dbUser=await User.findOne({email:req.body.email});if(dbUser)user={id:String(dbUser._id),email:dbUser.email,organizationId:String(dbUser.organizationId)}}if(!user)return res.json({message:'If the account exists, reset instructions have been sent.'});const token=crypto.randomBytes(24).toString('hex');resetTokens.set(token,{userId:user.id,organizationId:user.organizationId,expires:Date.now()+15*60*1000});const delivery=await sendPasswordResetEmail({email:user.email,token});res.json({message:'If the account exists, reset instructions have been sent.',...(process.env.NODE_ENV==='production'?{}:{developmentResetToken:token,developmentResetUrl:delivery.resetUrl})})})
app.post('/api/auth/reset-password',authLimiter,async(req,res)=>{const entry=resetTokens.get(req.body.token);if(!entry||entry.expires<Date.now())return res.status(400).json({message:'This reset link is invalid or expired.'});if(!req.body.password||req.body.password.length<8)return res.status(400).json({message:'Password must be at least 8 characters.'});const hash=await bcrypt.hash(req.body.password,10);if(mongoEnabled){const user=await User.findByIdAndUpdate(entry.userId,{passwordHash:hash},{new:true});if(!user)return res.status(404).json({message:'Account not found.'});await AuditLog.create({organizationId:user.organizationId,userId:user._id,action:'PASSWORD_RESET',entity:'User',entityId:String(user._id)})}else{const user=users.find(item=>item.id===entry.userId);if(!user)return res.status(404).json({message:'Account not found.'});user.password=hash;audit(user,'PASSWORD_RESET','User',user.id)}resetTokens.delete(req.body.token);res.json({message:'Password reset successful. Please sign in.'})})
app.get('/api/vehicles',auth(),async(req,res)=>{let rows=mongoEnabled?(await Vehicle.find({organizationId:req.user.organizationId}).lean()).map(serializeVehicle):scoped(vehicles,req.user);if(req.query.status)rows=rows.filter(vehicle=>vehicle.status===req.query.status);if(req.query.risk)rows=rows.filter(vehicle=>(Number(vehicle.health)<60)===(req.query.risk==='IMMEDIATE'));res.json(paged(rows,req.query))})
app.get('/api/vehicles/:id',auth(),async(req,res)=>{const row=mongoEnabled?(mongoose.isValidObjectId(req.params.id)&&await Vehicle.findOne({_id:req.params.id,organizationId:req.user.organizationId}).lean()):scoped(vehicles,req.user).find(vehicle=>vehicle.id===req.params.id);if(!row)return res.status(404).json({message:'Vehicle not found.'});res.json(mongoEnabled?serializeVehicle(row):row)})
app.post('/api/vehicles',auth(['OWNER']),async(req,res)=>{const {vehicleId,driverId=null,status='ON_ROAD',health=100,location={}}=req.body;if(!vehicleId||!String(vehicleId).trim())return res.status(400).json({message:'Vehicle ID is required.'});if(!Number.isFinite(Number(health))||Number(health)<0||Number(health)>100)return res.status(400).json({message:'Health must be between 0 and 100.'});if(mongoEnabled){if(driverId&&(!mongoose.isValidObjectId(driverId)||!await User.exists({_id:driverId,organizationId:req.user.organizationId,role:'DRIVER'})))return res.status(400).json({message:'Driver must belong to this organization.'});const vehicle=await Vehicle.create({organizationId:req.user.organizationId,vehicleId:String(vehicleId).trim(),driverId:driverId||null,status,health:Number(health),location});await AuditLog.create({organizationId:req.user.organizationId,userId:req.user.id,action:'VEHICLE_CREATED',entity:'Vehicle',entityId:String(vehicle._id)});return res.status(201).json(serializeVehicle(vehicle))}const vehicle={id:`vehicle-${Date.now()}`,organizationId:req.user.organizationId,vehicleId:String(vehicleId).trim(),driverId,status,health:Number(health),location};vehicles.unshift(vehicle);audit(req.user,'VEHICLE_CREATED','Vehicle',vehicle.id);res.status(201).json(vehicle)})
app.patch('/api/vehicles/:id',auth(['OWNER']),async(req,res)=>{const allowed=['driverId','status','health','location'];const changes=Object.fromEntries(Object.entries(req.body).filter(([key])=>allowed.includes(key)));if('health'in changes&&(!Number.isFinite(Number(changes.health))||Number(changes.health)<0||Number(changes.health)>100))return res.status(400).json({message:'Health must be between 0 and 100.'});if(mongoEnabled){if(!mongoose.isValidObjectId(req.params.id))return res.status(400).json({message:'Invalid vehicle identifier.'});if(changes.driverId&&(!mongoose.isValidObjectId(changes.driverId)||!await User.exists({_id:changes.driverId,organizationId:req.user.organizationId,role:'DRIVER'})))return res.status(400).json({message:'Driver must belong to this organization.'});const vehicle=await Vehicle.findOneAndUpdate({_id:req.params.id,organizationId:req.user.organizationId},changes,{new:true}).lean();if(!vehicle)return res.status(404).json({message:'Vehicle not found.'});await AuditLog.create({organizationId:req.user.organizationId,userId:req.user.id,action:'VEHICLE_UPDATED',entity:'Vehicle',entityId:req.params.id});return res.json(serializeVehicle(vehicle))}const vehicle=scoped(vehicles,req.user).find(item=>item.id===req.params.id);if(!vehicle)return res.status(404).json({message:'Vehicle not found.'});Object.assign(vehicle,changes);audit(req.user,'VEHICLE_UPDATED','Vehicle',vehicle.id);res.json(vehicle)})
app.get('/api/tickets',auth(),async(req,res)=>{let rows;if(mongoEnabled){const docs=await RepairTicket.find({organizationId:req.user.organizationId}).populate('vehicleId').lean();rows=docs.map(serializeTicket).filter(ticket=>req.user.role!=='WORKER'||ticket.workerId===req.user.id)}else rows=scoped(tickets,req.user).filter(t=>req.user.role!=='WORKER'||t.workerId===req.user.id);if(req.query.status)rows=rows.filter(ticket=>ticket.status===req.query.status);if(req.query.risk)rows=rows.filter(ticket=>ticket.risk===req.query.risk);if(req.query.search){const query=req.query.search.toLowerCase();rows=rows.filter(ticket=>`${ticket.vehicle} ${ticket.fault}`.toLowerCase().includes(query))}rows.sort((a,b)=>String(a.deadline||'').localeCompare(String(b.deadline||'')));res.json(paged(rows,req.query))})
app.get('/api/tickets/:id',auth(),async(req,res)=>{let ticket;if(mongoEnabled){if(!mongoose.isValidObjectId(req.params.id))return res.status(400).json({message:'Invalid ticket identifier.'});ticket=await RepairTicket.findOne({_id:req.params.id,organizationId:req.user.organizationId}).populate('vehicleId').lean();if(ticket&&req.user.role==='WORKER'&&String(ticket.workerId)!==req.user.id)ticket=null;ticket=ticket&&serializeTicket(ticket)}else{ticket=scoped(tickets,req.user).find(item=>item.id===req.params.id);if(ticket&&req.user.role==='WORKER'&&ticket.workerId!==req.user.id)ticket=null}if(!ticket)return res.status(404).json({message:'Ticket not found.'});res.json(ticket)})
app.get('/api/tasks/my',auth(['WORKER']),async(req,res)=>{let rows;if(mongoEnabled){rows=(await RepairTicket.find({organizationId:req.user.organizationId,workerId:req.user.id}).populate('vehicleId').lean()).map(serializeTicket)}else rows=scoped(tickets,req.user).filter(ticket=>ticket.workerId===req.user.id);res.json(paged(rows,req.query))})
app.get('/api/workers',auth(['OWNER']),async(req,res)=>{if(mongoEnabled){const [workers,activeTickets]=await Promise.all([User.find({organizationId:req.user.organizationId,role:'WORKER',active:true}).lean(),RepairTicket.find({organizationId:req.user.organizationId,status:{$ne:'COMPLETED'}}).lean()]);return res.json(workers.map(worker=>{const task=activeTickets.find(ticket=>String(ticket.workerId)===String(worker._id));return {id:String(worker._id),name:worker.name,status:task?'BUSY':'AVAILABLE',attendance:worker.profile?.checkedIn?'CHECKED_IN':'OFFLINE',currentTask:task?String(task._id):null}}))}res.json(users.filter(user=>user.organizationId===req.user.organizationId&&user.role==='WORKER'&&user.active).map(worker=>{const task=tickets.find(ticket=>ticket.workerId===worker.id&&ticket.status!=='COMPLETED');return {id:worker.id,name:worker.name,status:task?'BUSY':'AVAILABLE',attendance:'CHECKED_IN',currentTask:task?.id||null}}))})
app.post('/api/sensors/telemetry',auth(['OWNER','DRIVER']),async(req,res)=>{const {vehicleId,metrics={}}=req.body;if(!vehicleId)return res.status(400).json({message:'Vehicle ID is required.'});if(mongoEnabled){if(!mongoose.isValidObjectId(vehicleId))return res.status(400).json({message:'Invalid vehicle identifier.'});const vehicle=await Vehicle.findOne({_id:vehicleId,organizationId:req.user.organizationId});if(!vehicle)return res.status(404).json({message:'Vehicle not found.'});const reading=await SensorReading.create({organizationId:req.user.organizationId,vehicleId:vehicle._id,metrics});return res.status(201).json({id:String(reading._id),vehicleId:String(vehicle._id),metrics:reading.metrics,timestamp:reading.createdAt})}const vehicle=scoped(vehicles,req.user).find(item=>item.id===vehicleId);if(!vehicle)return res.status(404).json({message:'Vehicle not found.'});const reading={id:`sensor-${Date.now()}`,organizationId:req.user.organizationId,vehicleId,metrics,timestamp:new Date().toISOString()};records.unshift(reading);res.status(201).json(reading)})
app.get('/api/sensors/:vehicleId/latest',auth(),async(req,res)=>{if(mongoEnabled){if(!mongoose.isValidObjectId(req.params.vehicleId))return res.status(400).json({message:'Invalid vehicle identifier.'});const reading=await SensorReading.findOne({organizationId:req.user.organizationId,vehicleId:req.params.vehicleId}).sort({createdAt:-1}).lean();return reading?res.json({id:String(reading._id),vehicleId:String(reading.vehicleId),metrics:reading.metrics,timestamp:reading.createdAt}):res.status(404).json({message:'No sensor readings found.'})}const reading=scoped(records,req.user).find(item=>item.vehicleId===req.params.vehicleId&&item.metrics);if(!reading)return res.status(404).json({message:'No sensor readings found.'});res.json(reading)})
app.get('/api/sensors/:vehicleId/history',auth(),async(req,res)=>{if(mongoEnabled){if(!mongoose.isValidObjectId(req.params.vehicleId))return res.status(400).json({message:'Invalid vehicle identifier.'});const rows=await SensorReading.find({organizationId:req.user.organizationId,vehicleId:req.params.vehicleId}).sort({createdAt:-1}).limit(Math.min(Number(req.query.limit)||50,200)).lean();return res.json(rows.map(row=>({id:String(row._id),vehicleId:String(row.vehicleId),metrics:row.metrics,timestamp:row.createdAt})))}res.json(scoped(records,req.user).filter(item=>item.vehicleId===req.params.vehicleId&&item.metrics).slice(0,Math.min(Number(req.query.limit)||50,200)))})
app.post('/api/predictions/analyze',auth(['OWNER','DRIVER']),async(req,res)=>{const prediction=predictMaintenance(req.body.metrics||{});const {vehicleId}=req.body;if(mongoEnabled){if(!vehicleId||!mongoose.isValidObjectId(vehicleId))return res.status(400).json({message:'A valid vehicle ID is required.'});const vehicle=await Vehicle.findOne({_id:vehicleId,organizationId:req.user.organizationId});if(!vehicle)return res.status(404).json({message:'Vehicle not found.'});const saved=await Prediction.create({organizationId:req.user.organizationId,vehicleId:vehicle._id,...prediction});return res.status(201).json({id:String(saved._id),vehicleId:String(vehicle._id),...prediction,timestamp:saved.createdAt})}const saved={id:`prediction-${Date.now()}`,organizationId:req.user.organizationId,vehicleId,...prediction,timestamp:new Date().toISOString()};records.unshift(saved);res.status(201).json(saved)})
app.get('/api/predictions',auth(),async(req,res)=>{if(mongoEnabled){const rows=await Prediction.find({organizationId:req.user.organizationId}).sort({createdAt:-1}).limit(Math.min(Number(req.query.limit)||50,200)).lean();return res.json(rows.map(row=>({id:String(row._id),vehicleId:String(row.vehicleId),fault:row.fault,risk:row.risk,rootCause:row.rootCause,confidence:row.confidence,timestamp:row.createdAt})))}res.json(scoped(records,req.user).filter(item=>item.confidence).slice(0,Math.min(Number(req.query.limit)||50,200)))})
app.get('/api/predictions/:vehicleId',auth(),async(req,res)=>{if(mongoEnabled){if(!mongoose.isValidObjectId(req.params.vehicleId))return res.status(400).json({message:'Invalid vehicle identifier.'});const rows=await Prediction.find({organizationId:req.user.organizationId,vehicleId:req.params.vehicleId}).sort({createdAt:-1}).lean();return res.json(rows.map(row=>({id:String(row._id),vehicleId:String(row.vehicleId),fault:row.fault,risk:row.risk,rootCause:row.rootCause,confidence:row.confidence,timestamp:row.createdAt})))}res.json(scoped(records,req.user).filter(item=>item.vehicleId===req.params.vehicleId&&item.confidence))})
app.post('/api/telemetry/simulate',auth(['OWNER']),async(req,res)=>{const prediction=predictMaintenance(req.body.metrics||{batteryVoltage:req.body.risk==='IMMEDIATE'?11.4:12.2,brakePadMm:req.body.risk==='SHORT-TERM'?3.5:7});const deadline=new Date(Date.now()+(prediction.risk==='IMMEDIATE'?4:24)*3600000);if(mongoEnabled){const vehicle=await Vehicle.findOne({organizationId:req.user.organizationId,vehicleId:req.body.vehicleLabel||'TRUCK #091'});if(!vehicle)return res.status(404).json({message:'Demo vehicle not found in this organization.'});vehicle.health=prediction.risk==='IMMEDIATE'?42:prediction.risk==='SHORT-TERM'?68:88;await vehicle.save();const created=await RepairTicket.create({organizationId:req.user.organizationId,vehicleId:vehicle._id,fault:prediction.fault,risk:prediction.risk,rootCause:prediction.rootCause,confidence:prediction.confidence,status:'ASSIGNED',deadline});const ticket=serializeTicket({...created.toObject(),vehicleId:vehicle});await Promise.all([AuditLog.create({organizationId:req.user.organizationId,userId:req.user.id,action:'TICKET_CREATED',entity:'RepairTicket',entityId:String(created._id)}),Notification.create({organizationId:req.user.organizationId,message:`New ${prediction.risk} risk detected for ${vehicle.vehicleId}.`})]);io.to(req.user.organizationId).emit('ticket:created',ticket);return res.status(201).json(ticket)}const vehicle=vehicles.find(v=>v.id===req.body.vehicleId)||vehicles.find(v=>v.id==='vehicle-091');vehicle.health=prediction.risk==='IMMEDIATE'?42:prediction.risk==='SHORT-TERM'?68:88;const ticket={id:`UT-${Date.now()}`,organizationId:req.user.organizationId,vehicleId:vehicle.id,vehicle:vehicle.vehicleId,fault:prediction.fault,risk:prediction.risk,rootCause:prediction.rootCause,confidence:prediction.confidence,status:'ASSIGNED',workerId:null,deadline:deadline.toISOString()};tickets.unshift(ticket);audit(req.user,'TICKET_CREATED','RepairTicket',ticket.id);notify(org,null,`New ${prediction.risk} risk detected for ${vehicle.vehicleId}.`);io.to(org).emit('ticket:created',ticket);res.status(201).json(ticket)})
app.post('/api/tickets/:id/assign',auth(['OWNER']),async(req,res)=>{const deadline=req.body.deadline?new Date(req.body.deadline):null;if(req.body.deadline&&Number.isNaN(deadline.getTime()))return res.status(400).json({message:'Provide a valid repair deadline.'});if(mongoEnabled){if(!mongoose.isValidObjectId(req.params.id)||!mongoose.isValidObjectId(req.body.workerId))return res.status(400).json({message:'Invalid ticket or worker identifier.'});const [ticket,worker]=await Promise.all([RepairTicket.findOne({_id:req.params.id,organizationId:req.user.organizationId}).populate('vehicleId'),User.findOne({_id:req.body.workerId,organizationId:req.user.organizationId,role:'WORKER',active:true})]);if(!ticket||!worker)return res.status(404).json({message:'Ticket or active worker not found.'});ticket.workerId=worker._id;ticket.status='ASSIGNED';if(deadline)ticket.deadline=deadline;await ticket.save();await Promise.all([Notification.create({organizationId:req.user.organizationId,userId:worker._id,message:`New repair task assigned: ${ticket.vehicleId.vehicleId}.`}),AuditLog.create({organizationId:req.user.organizationId,userId:req.user.id,action:'TICKET_ASSIGNED',entity:'RepairTicket',entityId:String(ticket._id)})]);const payload=serializeTicket(ticket);io.to(String(worker._id)).emit('ticket:assigned',payload);io.to(req.user.organizationId).emit('ticket:updated',payload);return res.json(payload)}const t=scoped(tickets,req.user).find(x=>x.id===req.params.id);const worker=users.find(x=>x.id===req.body.workerId&&x.organizationId===req.user.organizationId&&x.role==='WORKER'&&x.active);if(!t||!worker)return res.status(404).json({message:'Ticket or active worker not found.'});t.workerId=worker.id;t.status='ASSIGNED';if(deadline)t.deadline=deadline.toISOString();audit(req.user,'TICKET_ASSIGNED','RepairTicket',t.id);notify(org,worker.id,`New repair task assigned: ${t.vehicle}.`);io.to(org).emit('ticket:updated',t);res.json(t)})
app.post('/api/tickets/:id/status',auth(['WORKER']),async(req,res)=>{const allowed={ASSIGNED:'IN_PROGRESS',IN_PROGRESS:'COMPLETED'};if(mongoEnabled){if(!mongoose.isValidObjectId(req.params.id))return res.status(400).json({message:'Invalid ticket identifier.'});const ticket=await RepairTicket.findOne({_id:req.params.id,organizationId:req.user.organizationId,workerId:req.user.id}).populate('vehicleId');if(!ticket)return res.status(404).json({message:'Assigned ticket not found.'});if(allowed[ticket.status]!==req.body.status)return res.status(400).json({message:'Invalid ticket transition.'});ticket.status=req.body.status;await ticket.save();const action=ticket.status==='COMPLETED'?'TASK_COMPLETED':'TASK_STARTED';await AuditLog.create({organizationId:req.user.organizationId,userId:req.user.id,action,entity:'RepairTicket',entityId:String(ticket._id)});if(ticket.status==='COMPLETED'){ticket.vehicleId.health=96;ticket.vehicleId.status='ON_ROAD';await ticket.vehicleId.save();await MaintenanceRecord.create({organizationId:req.user.organizationId,vehicleId:ticket.vehicleId._id,ticketId:ticket._id,workerId:req.user.id,notes:req.body.notes||''});await Notification.create({organizationId:req.user.organizationId,message:`${ticket.vehicleId.vehicleId} repair completed.`})}const payload=serializeTicket(ticket);io.to(req.user.organizationId).emit('ticket:updated',payload);return res.json(payload)}const t=scoped(tickets,req.user).find(x=>x.id===req.params.id&&x.workerId===req.user.id);if(!t)return res.status(404).json({message:'Assigned ticket not found.'});if(allowed[t.status]!==req.body.status)return res.status(400).json({message:'Invalid ticket transition.'});t.status=req.body.status;audit(req.user,t.status==='COMPLETED'?'TASK_COMPLETED':'TASK_STARTED','RepairTicket',t.id);if(t.status==='COMPLETED'){records.unshift({id:`maint-${Date.now()}`,organizationId:org,ticketId:t.id,vehicle:t.vehicle,workerId:req.user.id,notes:req.body.notes||'',createdAt:new Date().toISOString()});const vehicle=vehicles.find(v=>v.id===t.vehicleId);if(vehicle){vehicle.health=96;vehicle.status='ON_ROAD'}notify(org,'owner-1',`${t.vehicle} repair completed.`)}io.to(org).emit('ticket:updated',t);res.json(t)})
app.get('/api/notifications',auth(),async(req,res)=>{if(mongoEnabled){const rows=await Notification.find({organizationId:req.user.organizationId,$or:[{userId:req.user.id},{userId:null}]}).sort({createdAt:-1}).lean();return res.json(rows.map(row=>({id:String(row._id),message:row.message,read:row.read,timestamp:row.createdAt})))}res.json(scoped(notifications,req.user).filter(n=>!n.userId||n.userId===req.user.id))})
app.patch('/api/notifications/:id/read',auth(),async(req,res)=>{if(mongoEnabled){if(!mongoose.isValidObjectId(req.params.id))return res.status(400).json({message:'Invalid notification identifier.'});const notice=await Notification.findOneAndUpdate({_id:req.params.id,organizationId:req.user.organizationId,$or:[{userId:req.user.id},{userId:null}]},{read:true},{new:true}).lean();if(!notice)return res.status(404).json({message:'Notification not found.'});return res.json({id:String(notice._id),message:notice.message,read:notice.read,timestamp:notice.createdAt})}const notice=scoped(notifications,req.user).find(item=>item.id===req.params.id&&(!item.userId||item.userId===req.user.id));if(!notice)return res.status(404).json({message:'Notification not found.'});notice.read=true;res.json(notice)})
app.get('/api/maintenance',auth(),async(req,res)=>{if(mongoEnabled){const rows=await MaintenanceRecord.find({organizationId:req.user.organizationId}).populate('vehicleId').sort({createdAt:-1}).lean();return res.json(rows.map(row=>({id:String(row._id),vehicle:row.vehicleId?.vehicleId,ticketId:String(row.ticketId),workerId:String(row.workerId),notes:row.notes,proofUrl:row.proofUrl,createdAt:row.createdAt})))}res.json(scoped(records,req.user))})
app.get('/api/audit-logs',auth(['OWNER']),async(req,res)=>{if(mongoEnabled){const rows=await AuditLog.find({organizationId:req.user.organizationId}).sort({createdAt:-1}).lean();return res.json(rows.map(row=>({id:String(row._id),action:row.action,entity:row.entity,entityId:row.entityId,timestamp:row.createdAt,userId:String(row.userId)})))}res.json(scoped(audits,req.user))})
app.get('/api/analytics',auth(['OWNER']),async(req,res)=>{if(mongoEnabled){const [fleet,ticketRows]=await Promise.all([Vehicle.find({organizationId:req.user.organizationId}).lean(),RepairTicket.find({organizationId:req.user.organizationId}).lean()]);const distribution={immediate:0,shortTerm:0,longTerm:0};ticketRows.forEach(ticket=>{if(ticket.risk==='IMMEDIATE')distribution.immediate+=1;if(ticket.risk==='SHORT-TERM')distribution.shortTerm+=1;if(ticket.risk==='LONG-TERM')distribution.longTerm+=1});const completed=ticketRows.filter(ticket=>ticket.status==='COMPLETED').length;return res.json({fleetHealth:fleet.length?Math.round(fleet.reduce((sum,vehicle)=>sum+(vehicle.health||0),0)/fleet.length):0,activeRepairs:ticketRows.filter(ticket=>ticket.status!=='COMPLETED').length,firstTimeFixRate:ticketRows.length?Math.round((completed/ticketRows.length)*100):0,downtimeHours:ticketRows.filter(ticket=>ticket.status!=='COMPLETED').length*4,riskDistribution:distribution})}res.json({fleetHealth:78,activeRepairs:tickets.filter(t=>t.status!=='COMPLETED').length,firstTimeFixRate:92,downtimeHours:18,riskDistribution:{immediate:2,shortTerm:3,longTerm:2}})})
app.get('/api/analytics/:report',auth(['OWNER']),async(req,res,next)=>{if(!['fleet','repairs','downtime'].includes(req.params.report))return next();const fleet=mongoEnabled?(await Vehicle.find({organizationId:req.user.organizationId}).lean()):scoped(vehicles,req.user);const ticketRows=mongoEnabled?(await RepairTicket.find({organizationId:req.user.organizationId}).lean()):scoped(tickets,req.user);const completed=ticketRows.filter(ticket=>ticket.status==='COMPLETED').length;const data={fleet:{fleetHealth:fleet.length?Math.round(fleet.reduce((sum,vehicle)=>sum+(vehicle.health||0),0)/fleet.length):0,totalVehicles:fleet.length},repairs:{activeRepairs:ticketRows.filter(ticket=>ticket.status!=='COMPLETED').length,completedRepairs:completed,firstTimeFixRate:ticketRows.length?Math.round(completed/ticketRows.length*100):0},downtime:{downtimeHours:ticketRows.filter(ticket=>ticket.status!=='COMPLETED').length*4,estimatedSavingsHours:completed*2}};res.json(data[req.params.report])})
app.get('/api/driver/vehicle',auth(['DRIVER']),async(req,res)=>{if(mongoEnabled){const vehicle=await Vehicle.findOne({organizationId:req.user.organizationId,driverId:req.user.id}).lean();if(!vehicle)return res.status(404).json({message:'No vehicle is assigned to this driver.'});const ticket=await RepairTicket.findOne({organizationId:req.user.organizationId,vehicleId:vehicle._id,status:{$ne:'COMPLETED'}}).sort({createdAt:-1}).lean();return res.json({vehicle:serializeVehicle(vehicle),risk:ticket?.risk||'HEALTHY',fault:ticket?.fault||null,metrics:{temperature:91,batteryVoltage:vehicle.health<60?11.4:14.1,fuel:68}})}const vehicle=vehicles.find(item=>item.driverId===req.user.id);if(!vehicle)return res.status(404).json({message:'No vehicle is assigned to this driver.'});const ticket=tickets.find(item=>item.vehicleId===vehicle.id&&item.status!=='COMPLETED');res.json({vehicle:serializeVehicle(vehicle),risk:ticket?.risk||'HEALTHY',fault:ticket?.fault||null,metrics:{temperature:91,batteryVoltage:vehicle.health<60?11.4:14.1,fuel:68}})})
app.post('/api/driver/check-in',auth(['DRIVER']),async(req,res)=>{if(mongoEnabled){await User.findByIdAndUpdate(req.user.id,{$set:{'profile.checkedIn':true}});await AuditLog.create({organizationId:req.user.organizationId,userId:req.user.id,action:'DRIVER_CHECK_IN',entity:'User',entityId:req.user.id})}else audit(req.user,'DRIVER_CHECK_IN','User',req.user.id);res.json({checkedIn:true})})
app.post('/api/driver/check-out',auth(['DRIVER']),async(req,res)=>{if(mongoEnabled){await User.findByIdAndUpdate(req.user.id,{$set:{'profile.checkedIn':false}});await AuditLog.create({organizationId:req.user.organizationId,userId:req.user.id,action:'DRIVER_CHECK_OUT',entity:'User',entityId:req.user.id})}else audit(req.user,'DRIVER_CHECK_OUT','User',req.user.id);res.json({checkedIn:false})})
app.post('/api/driver/dvir',auth(['DRIVER']),(req,res)=>{audit(req.user,'DVIR_SUBMITTED','Vehicle',req.body.vehicleId||'vehicle-245');res.status(201).json({message:'DVIR submitted.'})})
app.post('/api/driver/sos',auth(['DRIVER']),(req,res)=>{audit(req.user,'DRIVER_SOS','Vehicle',req.body.vehicleId||'vehicle-245');notify(org,'owner-1',`SOS raised by ${req.user.name}.`);res.status(201).json({message:'SOS sent to fleet operations.'})})
app.post('/api/worker/check-in',auth(['WORKER']),async(req,res)=>{if(mongoEnabled){await User.findByIdAndUpdate(req.user.id,{$set:{'profile.checkedIn':true}});await AuditLog.create({organizationId:req.user.organizationId,userId:req.user.id,action:'WORKER_CHECK_IN',entity:'User',entityId:req.user.id})}else audit(req.user,'WORKER_CHECK_IN','User',req.user.id);res.json({checkedIn:true,message:'Worker attendance recorded.'})})
app.get('/api/ar/procedures/:fault',auth(['WORKER']),async(req,res)=>{const fallbackSteps=['Secure vehicle and isolate power','Inspect physical connections','Measure the affected circuit','Replace failed component and verify'];if(mongoEnabled){const procedure=await ARProcedure.findOne({fault:{$regex:req.params.fault,$options:'i'}}).lean();if(procedure)return res.json({mode:'webxr-fallback',fault:req.params.fault,steps:procedure.steps,modelUrl:procedure.modelUrl||null})}res.json({mode:'webxr-fallback',fault:req.params.fault,steps:fallbackSteps,modelUrl:null})})
app.post('/api/ai/repair-assistant',auth(['WORKER']),async(req,res)=>res.json(await answerRepairQuestion(req.body)))
app.post('/api/tickets/:id/proof',auth(['WORKER']),async(req,res)=>{const {imageUrl,notes=''}=req.body;if(mongoEnabled){if(!mongoose.isValidObjectId(req.params.id))return res.status(400).json({message:'Invalid ticket identifier.'});const ticket=await RepairTicket.findOne({_id:req.params.id,organizationId:req.user.organizationId,workerId:req.user.id});if(!ticket)return res.status(404).json({message:'Assigned ticket not found.'});const proofUrl=await saveRepairProof(imageUrl,String(ticket._id));await MaintenanceRecord.findOneAndUpdate({organizationId:req.user.organizationId,ticketId:ticket._id},{organizationId:req.user.organizationId,vehicleId:ticket.vehicleId,ticketId:ticket._id,workerId:req.user.id,notes,proofUrl},{upsert:true,new:true});await AuditLog.create({organizationId:req.user.organizationId,userId:req.user.id,action:'REPAIR_PROOF_ADDED',entity:'RepairTicket',entityId:String(ticket._id)});return res.json({message:'Repair proof saved.',proof:{proofUrl,notes}})}const ticket=scoped(tickets,req.user).find(t=>t.id===req.params.id&&t.workerId===req.user.id);if(!ticket)return res.status(404).json({message:'Assigned ticket not found.'});const proofUrl=await saveRepairProof(imageUrl,ticket.id);ticket.proof={proofUrl,notes,updatedAt:new Date().toISOString()};audit(req.user,'REPAIR_PROOF_ADDED','RepairTicket',ticket.id);res.json({message:'Repair proof saved.',proof:ticket.proof})})
app.get('/api/training/vr',auth(['WORKER']),(req,res)=>res.json({mode:'fallback',available:false,title:'Battery diagnostics training',message:'VR hardware was not detected. Use the interactive step-by-step repair guide on this device.'}))
io.use((socket,next)=>{try{const token=socket.handshake.auth?.token;if(!token)return next(new Error('Authentication required.'));socket.user=jwt.verify(token,jwtSecret);next()}catch{return next(new Error('Authentication required.'))}})
io.on('connection',socket=>{socket.join(socket.user.id);if(socket.user.role==='OWNER')socket.join(socket.user.organizationId)})
app.use(notFound)
app.use(errorHandler)
connectDatabase().then(connected=>{mongoEnabled=connected}).catch(error=>console.error('Database connection failed:',error.message)).finally(()=>http.listen(process.env.PORT||5000,()=>console.log('UTAP API listening')))
